# 本脚本要基于数据库配置表maintenance_deploy_config来执行，所有参数为必填
base:
  config:
    db:
      url: 192.168.0.69
      username: root
      password: '000000'
      db: ry-cloud

project:
  git:
    url: http://144.123.43.78:9208/gitlab/huangxupeng0831/dataplatform-ruoyi.git
    username: root
    password: wyz123!@#
    # git clone basepath
    base_clone_path: C:\\test2
    project_name: opsyndex-mengniu
    version: 1.0

# 对应了maintenance_deploy_config的service_name（用来区分环境变量，为未来的中心化上云服务提供基础）
deploy:
  java:
    # 相对base_clone_path路径
    uri:
    # 对应servicename
    deploy_names:
      - opsyndex-auth-test
      - opsyndex-system-test
    # id模式，定向发布，目前没有实现，给未来定向发布预留
    deploy_id:
    # 测试停留
    test_delay: 20
  vue:
    # 相对project.git.base_clone_path路径，可选，用于可以一个脚本工程同时发布前后台的场景
    uri: ruoyi-ui
    # 对应servicename
    deploy_names: vue-prod-test
  react:
message:
  # none/ding_group/ding/qwx/mail
  type: ding_group
  config:
    ding_group:
      access_token: a6c6f183c0b4f411028f828728cc731d811d5d1c3e50066597d50b0a90ce6d79
      secret: SECb0134d59803807164943ddd032314040d8588ff15635c7409a4bc899e1a45718
    ding:
    qwx:
    mail:
