# 本脚本要基于数据库配置表maintenance_deploy_config来执行，所有参数为必填
base:
  config:
    db:
      url: 192.168.0.69
      username: root
      password: '000000'
      db: ry-cloud
project:
  git:
    url: http://144.123.43.78:9208/gitlab/huangxupeng0831/dataplatform-ruoyi.git
    username: root
    password: wyz123!@#
    # git clone basepath
    base_clone_path: C:\\test2
    project_name: opsyndex-java
    version: 1.0

# 对应了maintenance_deploy_config的service_name（用来区分环境变量，为未来的中心化上云服务提供基础）
deploy:
  deploy_names:
    - opsyndex-auth
    - opsyndex-system
message:
  # none/ding_group/ding/qwx/mail
  type: ding
  config:
    ding_group:
    ding:
    qwx:
    mail:
