# 本脚本要基于数据库配置表maintenance_deploy_config来执行，所有参数为必填
base:
  config:
    db:
      url: 192.168.0.69
      port: 3306
      username: root
      password: '000000'
      db: ry-cloud

project:
  git:
    url: http://144.123.43.78:9208/gitlab/huangxupeng0831/dataplatform-ruoyi.git
    username: root
    password: wyz123!@#
    # 代码分支-默认master
    branch: feature/dev-20250628-publish
    # git clone basepath
    base_clone_path: E:\alp\project\mengniu
    project_name: opsyndex-mengniu
    version: 1.0


# 对应了maintenance_deploy_config的service_name（用来区分环境变量，为未来的中心化上云服务提供基础）
deploy:
  java:
    # 相对base_clone_path路径
    uri:
    # 对应servicename
    deploy_names:
#      - opsyndex-auth-test
#      - opsyndex-gateway-test
#      - opsyndex-system-test
#      - opsyndex-message-center-test
      - service-data-dts-test
#      - opsyndex-form-design-test
#      - opsyndex-document-test
#      - opsyndex-flow-realise-test
#      - opsyndex-download-center-test
#      - opsyndex-dataquality-test
      - data-metadata-service-test
      - data-metadata-service-console-test
      - data-market-service-test
      - data-market-service-mapping-test
#      - opsyndex-file-test
#      - mengniu-api-test
#      - opsyndex-rule-engine-test
    # id模式，定向发布，目前没有实现，给未来定向发布预留
    deploy_id:
    # 测试停留
    test_delay: 20
    # TODO:备份预留:
    backup:
      interval:
      size:
    # TODO:发布失败，自动回滚上个构件
    auto_roll_back:
  vue:
    # 相对project.git.base_clone_path路径，可选，用于可以一个脚本工程同时发布前后台的场景
    uri: ruoyi-ui
    # 对应servicename
    deploy_names:
    # TODO: 清空node_modules和package-lock去构建，避免有稀奇古怪的问题。
    clean_build: false
  react:
message:
  # none/ding_group/ding/qwx/mail
  type: ding_group
  config:
    ding_group:
#      access_token: a6c6f183c0b4f411028f828728cc731d811d5d1c3e50066597d50b0a90ce6d79 蒙牛内部
#      secret: SECb0134d59803807164943ddd032314040d8588ff15635c7409a4bc899e1a45718

        access_token: 508dc9040f4660229b6ae96eb02c64c3cebba080518be08db481fc3f931467f4 # opsyndex
        secret: SEC6d00bdfed15181ef1c93c6f4527893269656847cd55f248cefc6a4d3b327b1ce
    ding:
    qwx:
    mail:
