# 本脚本要基于数据库配置表maintenance_deploy_config来执行，所有参数为必填
base:
  config:
    db:
      url: 192.168.0.69
      username: root
      password: 000000
      db: ry-cloud
project:
  git:
    url: http://144.123.43.78:9208/gitlab/huangxupeng0831/dataplatform-ruoyi.git
    username: root
    password: wyz123!@#
    # git clone basepath
    base_clone_path: C:\test2
    project_name: opsyndex-java
    version: 1.0

# 对应了maintenance_deploy_config
deploy:
  deploy_names:
    - wyz
    - b
    - c
message:
  # none/ding_group/ding/qwx/mail
  type: ding
  config:
    ding_group:
    ding:
    qwx:
    mail:
